### ISSUE TITLE
Configuration Problem

### ISSUE THREAD

**Issue by bomba2834** [zKBTuran/boru#1]
**Boru** will not run when the **configuration file** is _missing_.
![2022-06-29_19-35](https://user-images.githubusercontent.com/101938906/176489674-9fd790e5-b111-497f-8455-fc5fc51e0bd2.png)

**Comment by zKBTuran** [comment]
nice issue fellow contributor
what did you do to cause that problem?

**Comment by zKBTuran** [comment]
Why the hell you rm'd the config file?

**Comment by pmagixc** [comment]
make empty config file
